/**
 * \file    Jenkinsfile
 * \brief   Jenkinsfile Groovy script
 *
 * Copyright (C) 2022 Deniz Eren <deniz.eren@outlook.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

node('jenkins_agent') {

    def buildpath = "/var/tmp/$NODE_NAME";

    try {
        stage('checkout and setup dev environment') {
            sh(script: """
                rm -rf $buildpath
                mkdir -p $buildpath
            """)

            checkout([$class: 'GitSCM',
                branches: [[name: '*/main']],
                extensions: [[$class: 'RelativeTargetDirectory',
                    relativeTargetDir: "$buildpath/dev-can-linux/"]],
                userRemoteConfigs: [[
                    credentialsId: '',
                    url: '/opt/dev-can-linux'
                ]]])

            def publisher = LastChanges.getLastChangesPublisher \
                null, "SIDE", "LINE", true, true, \
                "", "", "", "$buildpath/dev-can-linux", ""

            publisher.publishLastChanges()

            sh(script: """
                /opt/dev-can-linux/ci/jenkins/scripts/setup-dev-environment.sh \
                    -i /home/jenkins/Images \
                    -r /opt/dev-can-linux
            """)
        }

        stage('integration testing (with coverage)') {
            sh(script: """
                rm -rf /data/home/root/build_qcc_coverage

                /opt/dev-can-linux/ci/jenkins/scripts/integration-testing.sh -v \
                    -i /home/jenkins/Images \
                    -b /data/home/root/build_qcc_coverage \
                    -d mioe3680_pci \
                    -t Coverage \
                    -r 10

                docker exec --user root --workdir /root dev_env bash -c \
                    "source .profile \
                    && /root/dev-can-linux/dev/setup-profile.sh \
                    && cd /data/home/root/build_qcc_coverage \
                    && lcov --gcov-tool=\\\$QNX_HOST/usr/bin/ntox86_64-gcov \
                        -t \"test_coverage_results\" -o tests.info \
                        -c -d /data/home/root/build_qcc_coverage \
                        --base-directory=/root/dev-can-linux \
                        --no-external --quiet \
                    && genhtml -o /data/home/root/build_qcc_coverage/cov-html \
                        tests.info --quiet"

                rm -rf $WORKSPACE/test-coverage-qcc

                docker cp \
                    dev_env:/data/home/root/build_qcc_coverage/cov-html \
                        $WORKSPACE/test-coverage-qcc

            """)

            publishHTML(target : [allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'test-coverage-qcc',
                reportFiles: 'index.html',
                reportName: 'Coverage Report (QCC)',
                reportTitles: 'Coverage Report (QCC)'])
        }

        stage('release') {
            sh(script: """
                docker exec --user root --workdir /root dev_env \
                    bash -c "source .profile \
                        && /root/dev-can-linux/dev/setup-profile.sh \
                        && mkdir -p build_release \
                        && cd build_release \
                        && cmake -DCMAKE_BUILD_TYPE=Release \
                                ../dev-can-linux \
                        && make -j8 \
                        && cpack \
                        && DIR=\\\"Release/dev-can-linux/\\\$(date \\\"+%Y-%m-%d-%H%M%S%Z\\\")\\\" \
                        && mkdir -p \\\"\\\$DIR\\\" \
                        && cp dev-can-linux-*.tar.gz \\\"\\\$DIR\\\""

                docker cp \
                    dev_env:/root/build_release/Release/dev-can-linux \
                    /var/Release/
            """)
        }
    }
    catch (err) {
        currentBuild.result = 'FAILURE'
    }
    finally {
        stage('clean-up') {
            sh(script: """
                docker stop dev_env
                docker rm dev_env

                rm -rf $buildpath
            """)
        }
    }
}
